# Generated by Django 5.2.7 on 2025-11-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAdditionalMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255, unique=True)),
                ('data_model', models.CharField(max_length=255)),
                ('purpose_of_use', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
